/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type PackageCategory = { 'cultural' : null } |
  { 'desert' : null } |
  { 'luxury' : null } |
  { 'heritage' : null };
export interface Testimonial {
  'id' : bigint,
  'starRating' : bigint,
  'clientName' : string,
  'reviewText' : string,
  'avatarLabel' : string,
  'location' : string,
}
export interface TourPackage {
  'id' : bigint,
  'durationDays' : bigint,
  'title' : string,
  'featured' : boolean,
  'description' : string,
  'category' : PackageCategory,
  'priceUSD' : bigint,
}
export interface _SERVICE {
  'addTestimonial' : ActorMethod<
    [
      {
        'starRating' : bigint,
        'clientName' : string,
        'reviewText' : string,
        'avatarLabel' : string,
        'location' : string,
      },
    ],
    bigint
  >,
  'addTourPackage' : ActorMethod<
    [
      {
        'durationDays' : bigint,
        'title' : string,
        'featured' : boolean,
        'description' : string,
        'category' : PackageCategory,
        'priceUSD' : bigint,
      },
    ],
    bigint
  >,
  'getAllPackages' : ActorMethod<[], Array<TourPackage>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getPackage' : ActorMethod<[bigint], TourPackage>,
  'initialize' : ActorMethod<[], undefined>,
  'submitBooking' : ActorMethod<
    [
      {
        'customerName' : string,
        'specialRequests' : [] | [string],
        'destinationName' : string,
        'email' : string,
        'travelDate' : string,
        'phone' : string,
        'groupSize' : bigint,
      },
    ],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];