/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PackageCategory = IDL.Variant({
  'cultural' : IDL.Null,
  'desert' : IDL.Null,
  'luxury' : IDL.Null,
  'heritage' : IDL.Null,
});
export const TourPackage = IDL.Record({
  'id' : IDL.Nat,
  'durationDays' : IDL.Nat,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'description' : IDL.Text,
  'category' : PackageCategory,
  'priceUSD' : IDL.Nat,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'starRating' : IDL.Nat,
  'clientName' : IDL.Text,
  'reviewText' : IDL.Text,
  'avatarLabel' : IDL.Text,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  'addTestimonial' : IDL.Func(
      [
        IDL.Record({
          'starRating' : IDL.Nat,
          'clientName' : IDL.Text,
          'reviewText' : IDL.Text,
          'avatarLabel' : IDL.Text,
          'location' : IDL.Text,
        }),
      ],
      [IDL.Nat],
      [],
    ),
  'addTourPackage' : IDL.Func(
      [
        IDL.Record({
          'durationDays' : IDL.Nat,
          'title' : IDL.Text,
          'featured' : IDL.Bool,
          'description' : IDL.Text,
          'category' : PackageCategory,
          'priceUSD' : IDL.Nat,
        }),
      ],
      [IDL.Nat],
      [],
    ),
  'getAllPackages' : IDL.Func([], [IDL.Vec(TourPackage)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getPackage' : IDL.Func([IDL.Nat], [TourPackage], ['query']),
  'initialize' : IDL.Func([], [], []),
  'submitBooking' : IDL.Func(
      [
        IDL.Record({
          'customerName' : IDL.Text,
          'specialRequests' : IDL.Opt(IDL.Text),
          'destinationName' : IDL.Text,
          'email' : IDL.Text,
          'travelDate' : IDL.Text,
          'phone' : IDL.Text,
          'groupSize' : IDL.Nat,
        }),
      ],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PackageCategory = IDL.Variant({
    'cultural' : IDL.Null,
    'desert' : IDL.Null,
    'luxury' : IDL.Null,
    'heritage' : IDL.Null,
  });
  const TourPackage = IDL.Record({
    'id' : IDL.Nat,
    'durationDays' : IDL.Nat,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'description' : IDL.Text,
    'category' : PackageCategory,
    'priceUSD' : IDL.Nat,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'starRating' : IDL.Nat,
    'clientName' : IDL.Text,
    'reviewText' : IDL.Text,
    'avatarLabel' : IDL.Text,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    'addTestimonial' : IDL.Func(
        [
          IDL.Record({
            'starRating' : IDL.Nat,
            'clientName' : IDL.Text,
            'reviewText' : IDL.Text,
            'avatarLabel' : IDL.Text,
            'location' : IDL.Text,
          }),
        ],
        [IDL.Nat],
        [],
      ),
    'addTourPackage' : IDL.Func(
        [
          IDL.Record({
            'durationDays' : IDL.Nat,
            'title' : IDL.Text,
            'featured' : IDL.Bool,
            'description' : IDL.Text,
            'category' : PackageCategory,
            'priceUSD' : IDL.Nat,
          }),
        ],
        [IDL.Nat],
        [],
      ),
    'getAllPackages' : IDL.Func([], [IDL.Vec(TourPackage)], ['query']),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getPackage' : IDL.Func([IDL.Nat], [TourPackage], ['query']),
    'initialize' : IDL.Func([], [], []),
    'submitBooking' : IDL.Func(
        [
          IDL.Record({
            'customerName' : IDL.Text,
            'specialRequests' : IDL.Opt(IDL.Text),
            'destinationName' : IDL.Text,
            'email' : IDL.Text,
            'travelDate' : IDL.Text,
            'phone' : IDL.Text,
            'groupSize' : IDL.Nat,
          }),
        ],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };