/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TourPackage {
    id: bigint;
    durationDays: bigint;
    title: string;
    featured: boolean;
    description: string;
    category: PackageCategory;
    priceUSD: bigint;
}
export interface Testimonial {
    id: bigint;
    starRating: bigint;
    clientName: string;
    reviewText: string;
    avatarLabel: string;
    location: string;
}
export enum PackageCategory {
    cultural = "cultural",
    desert = "desert",
    luxury = "luxury",
    heritage = "heritage"
}
export interface backendInterface {
    addTestimonial(testimonial: {
        starRating: bigint;
        clientName: string;
        reviewText: string;
        avatarLabel: string;
        location: string;
    }): Promise<bigint>;
    addTourPackage(pkg: {
        durationDays: bigint;
        title: string;
        featured: boolean;
        description: string;
        category: PackageCategory;
        priceUSD: bigint;
    }): Promise<bigint>;
    getAllPackages(): Promise<Array<TourPackage>>;
    getAllTestimonials(): Promise<Array<Testimonial>>;
    getPackage(id: bigint): Promise<TourPackage>;
    initialize(): Promise<void>;
    submitBooking(booking: {
        customerName: string;
        specialRequests?: string;
        destinationName: string;
        email: string;
        travelDate: string;
        phone: string;
        groupSize: bigint;
    }): Promise<bigint>;
}
import type { PackageCategory as _PackageCategory, TourPackage as _TourPackage } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addTestimonial(arg0: {
        starRating: bigint;
        clientName: string;
        reviewText: string;
        avatarLabel: string;
        location: string;
    }): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTestimonial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTestimonial(arg0);
            return result;
        }
    }
    async addTourPackage(arg0: {
        durationDays: bigint;
        title: string;
        featured: boolean;
        description: string;
        category: PackageCategory;
        priceUSD: bigint;
    }): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTourPackage(to_candid_record_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTourPackage(to_candid_record_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllPackages(): Promise<Array<TourPackage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPackages();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPackages();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTestimonials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTestimonials();
            return result;
        }
    }
    async getPackage(arg0: bigint): Promise<TourPackage> {
        if (this.processError) {
            try {
                const result = await this.actor.getPackage(arg0);
                return from_candid_TourPackage_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPackage(arg0);
            return from_candid_TourPackage_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async initialize(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initialize();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initialize();
            return result;
        }
    }
    async submitBooking(arg0: {
        customerName: string;
        specialRequests?: string;
        destinationName: string;
        email: string;
        travelDate: string;
        phone: string;
        groupSize: bigint;
    }): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitBooking(to_candid_record_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitBooking(to_candid_record_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_PackageCategory_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PackageCategory): PackageCategory {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_TourPackage_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TourPackage): TourPackage {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    durationDays: bigint;
    title: string;
    featured: boolean;
    description: string;
    category: _PackageCategory;
    priceUSD: bigint;
}): {
    id: bigint;
    durationDays: bigint;
    title: string;
    featured: boolean;
    description: string;
    category: PackageCategory;
    priceUSD: bigint;
} {
    return {
        id: value.id,
        durationDays: value.durationDays,
        title: value.title,
        featured: value.featured,
        description: value.description,
        category: from_candid_PackageCategory_n7(_uploadFile, _downloadFile, value.category),
        priceUSD: value.priceUSD
    };
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cultural: null;
} | {
    desert: null;
} | {
    luxury: null;
} | {
    heritage: null;
}): PackageCategory {
    return "cultural" in value ? PackageCategory.cultural : "desert" in value ? PackageCategory.desert : "luxury" in value ? PackageCategory.luxury : "heritage" in value ? PackageCategory.heritage : value;
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TourPackage>): Array<TourPackage> {
    return value.map((x)=>from_candid_TourPackage_n5(_uploadFile, _downloadFile, x));
}
function to_candid_PackageCategory_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PackageCategory): _PackageCategory {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_record_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    durationDays: bigint;
    title: string;
    featured: boolean;
    description: string;
    category: PackageCategory;
    priceUSD: bigint;
}): {
    durationDays: bigint;
    title: string;
    featured: boolean;
    description: string;
    category: _PackageCategory;
    priceUSD: bigint;
} {
    return {
        durationDays: value.durationDays,
        title: value.title,
        featured: value.featured,
        description: value.description,
        category: to_candid_PackageCategory_n2(_uploadFile, _downloadFile, value.category),
        priceUSD: value.priceUSD
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    specialRequests?: string;
    destinationName: string;
    email: string;
    travelDate: string;
    phone: string;
    groupSize: bigint;
}): {
    customerName: string;
    specialRequests: [] | [string];
    destinationName: string;
    email: string;
    travelDate: string;
    phone: string;
    groupSize: bigint;
} {
    return {
        customerName: value.customerName,
        specialRequests: value.specialRequests ? candid_some(value.specialRequests) : candid_none(),
        destinationName: value.destinationName,
        email: value.email,
        travelDate: value.travelDate,
        phone: value.phone,
        groupSize: value.groupSize
    };
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PackageCategory): {
    cultural: null;
} | {
    desert: null;
} | {
    luxury: null;
} | {
    heritage: null;
} {
    return value == PackageCategory.cultural ? {
        cultural: null
    } : value == PackageCategory.desert ? {
        desert: null
    } : value == PackageCategory.luxury ? {
        luxury: null
    } : value == PackageCategory.heritage ? {
        heritage: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
